### ISSUE TITLE
[MacOS Catalina] No text on buttons...

### ISSUE THREAD

**Issue by michaelmort** [PXshadow/OpenLife#3]
I wanted to try this program out, but I can't read what I'm clicking! All of the buttons work and are clickable, but the text doesn't display! 

I'm running MacOS Catalina 10.15.1 in dark mode.
![Screen Shot 2020-04-17 at 6 34 26 PM](https://user-images.githubusercontent.com/45403228/79619219-48c02800-80da-11ea-9e9c-f9c041598933.png)

**Comment by PXshadow** [comment]
Hey @michaelmort sorry about that, currently I have not touched the launcher in a while and plan to in the future combine it with my client, Currently if you're looking for modded clients your only choice on mac is awbz, and for servers two hours one life and official one life are the only ones really standing with a decent size playerbase . So although I still think the launcher is a good idea it doesn't make a lot of sense currently with the limited amount of projects that have come out since then. However if that changes a standalone client will come back on the table but for now these features in a more minimal manner will be coming via the openlife client. And I will have 64 bit mac support so that will give another option for mac players that want to use a modded client.
